name: flutter_notes
description: A note taking app made with Flutter.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^8.1.1
  intl: ^0.17.0
  path_provider: ^2.0.11
  sqflite: ^2.2.0+3
  xml: ^6.1.0

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true